In [1]:
pip install pandas numpy nltk scikit-learn seaborn matplotlib

Looking in indexes: https://pypi.ci.artifacts.walmart.com/artifactory/api/pypi/pythonhosted-pypi-release-remote/simple
  Using cached https://pypi.ci.artifacts.walmart.com/artifactory/api/pypi/pythonhosted-pypi-release-remote/packages/packages/9c/b9/5cead4f63b6d31bdefeb21a679bc5a7f4aaf262ca7e07e2bc1c341b68470/pandas-2.2.3-cp39-cp39-macosx_11_0_arm64.whl (11.3 MB)
  Using cached https://pypi.ci.artifacts.walmart.com/artifactory/api/pypi/pythonhosted-pypi-release-remote/packages/packages/96/ff/06d1aa3eeb1c614eda245c1ba4fb88c483bee6520d361641331872ac4b82/numpy-2.0.2-cp39-cp39-macosx_14_0_arm64.whl (5.3 MB)
  Using cached https://pypi.ci.artifacts.walmart.com/artifactory/api/pypi/pythonhosted-pypi-release-remote/packages/packages/4d/66/7d9e26593edda06e8cb531874633f7c2372279c3b0f46235539fe546df8b/nltk-3.9.1-py3-none-any.whl (1.5 MB)
  Using cached https://pypi.ci.artifacts.walmart.com/artifactory/api/pypi/pythonhosted-pypi-release-remote/packages/packages/c6/96/e75df8bf7c25f83faadb26c456d6b

In [133]:
import pandas as pd
import numpy as np

In [4]:
car_df = pd.read_csv('./quikr_car.csv')
car_df.head(5)

name   company  year          Price  \
0    Hyundai Santro Xing XO eRLX Euro III   Hyundai  2007         80,000   
1                 Mahindra Jeep CL550 MDI  Mahindra  2006       4,25,000   
2              Maruti Suzuki Alto 800 Vxi    Maruti  2018  Ask For Price   
3  Hyundai Grand i10 Magna 1.2 Kappa VTVT   Hyundai  2014       3,25,000   
4        Ford EcoSport Titanium 1.5L TDCi      Ford  2014       5,75,000   

   kms_driven fuel_type  
0  45,000 kms    Petrol  
1      40 kms    Diesel  
2  22,000 kms    Petrol  
3  28,000 kms    Petrol  
4  36,000 kms    Diesel

In [27]:
print(car_df.shape)
car_df.info()

(892, 6)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 892 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        892 non-null    object
 1   company     892 non-null    object
 2   year        892 non-null    object
 3   Price       892 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: object(6)
memory usage: 41.9+ KB


# DATA QUALITY CHECK

In [7]:
car_df.isna().sum()

name           0
company        0
year           0
Price          0
kms_driven    52
fuel_type     55
dtype: int64

In [18]:
print(car_df.duplicated().sum())
car_df[car_df['name'] == 'Hyundai Santro Xing XO eRLX Euro III']

94


name  company  year   Price  kms_driven  \
0    Hyundai Santro Xing XO eRLX Euro III  Hyundai  2007  80,000  45,000 kms   
14   Hyundai Santro Xing XO eRLX Euro III  Hyundai  2007  80,000  45,000 kms   
284  Hyundai Santro Xing XO eRLX Euro III  Hyundai  2000  59,000  56,450 kms   

    fuel_type  
0      Petrol  
14     Petrol  
284    Petrol

In [29]:
car_df['year'].unique()
# FIX GARBAGE VALUES
# Convert to int

array(['2007', '2006', '2018', '2014', '2015', '2012', '2013', '2016',
       '2010', '2017', '2008', '2011', '2019', '2009', '2005', '2000',
       '...', '150k', 'TOUR', '2003', 'r 15', '2004', 'Zest', '/-Rs',
       'sale', '1995', 'ara)', '2002', 'SELL', '2001', 'tion', 'odel',
       '2 bs', 'arry', 'Eon', 'o...', 'ture', 'emi', 'car', 'able', 'no.',
       'd...', 'SALE', 'digo', 'sell', 'd Ex', 'n...', 'e...', 'D...',
       ', Ac', 'go .', 'k...', 'o c4', 'zire', 'cent', 'Sumo', 'cab',
       't xe', 'EV2', 'r...', 'zest'], dtype=object)

In [30]:
car_df['Price'].unique()
# FIX ASK FOR PRICE
# Convert to int

array(['80,000', '4,25,000', 'Ask For Price', '3,25,000', '5,75,000',
       '1,75,000', '1,90,000', '8,30,000', '2,50,000', '1,82,000',
       '3,15,000', '4,15,000', '3,20,000', '10,00,000', '5,00,000',
       '3,50,000', '1,60,000', '3,10,000', '75,000', '1,00,000',
       '2,90,000', '95,000', '1,80,000', '3,85,000', '1,05,000',
       '6,50,000', '6,89,999', '4,48,000', '5,49,000', '5,01,000',
       '4,89,999', '2,80,000', '3,49,999', '2,84,999', '3,45,000',
       '4,99,999', '2,35,000', '2,49,999', '14,75,000', '3,95,000',
       '2,20,000', '1,70,000', '85,000', '2,00,000', '5,70,000',
       '1,10,000', '4,48,999', '18,91,111', '1,59,500', '3,44,999',
       '4,49,999', '8,65,000', '6,99,000', '3,75,000', '2,24,999',
       '12,00,000', '1,95,000', '3,51,000', '2,40,000', '90,000',
       '1,55,000', '6,00,000', '1,89,500', '2,10,000', '3,90,000',
       '1,35,000', '16,00,000', '7,01,000', '2,65,000', '5,25,000',
       '3,72,000', '6,35,000', '5,50,000', '4,85,000', '3,29,5

In [34]:
car_df['kms_driven'].unique()
# FIX GARBAGE VALUES like petrol
# Convert to int

array(['45,000 kms', '40 kms', '22,000 kms', '28,000 kms', '36,000 kms',
       '59,000 kms', '41,000 kms', '25,000 kms', '24,530 kms',
       '60,000 kms', '30,000 kms', '32,000 kms', '48,660 kms',
       '4,000 kms', '16,934 kms', '43,000 kms', '35,550 kms',
       '39,522 kms', '39,000 kms', '55,000 kms', '72,000 kms',
       '15,975 kms', '70,000 kms', '23,452 kms', '35,522 kms',
       '48,508 kms', '15,487 kms', '82,000 kms', '20,000 kms',
       '68,000 kms', '38,000 kms', '27,000 kms', '33,000 kms',
       '46,000 kms', '16,000 kms', '47,000 kms', '35,000 kms',
       '30,874 kms', '15,000 kms', '29,685 kms', '1,30,000 kms',
       '19,000 kms', nan, '54,000 kms', '13,000 kms', '38,200 kms',
       '50,000 kms', '13,500 kms', '3,600 kms', '45,863 kms',
       '60,500 kms', '12,500 kms', '18,000 kms', '13,349 kms',
       '29,000 kms', '44,000 kms', '42,000 kms', '14,000 kms',
       '49,000 kms', '36,200 kms', '51,000 kms', '1,04,000 kms',
       '33,333 kms', '33,600 kms', '5,

In [35]:
car_df['fuel_type'].unique()
# fix nan values

array(['Petrol', 'Diesel', nan, 'LPG'], dtype=object)

In [37]:
car_df['name'].unique()
# lets keep first 3 words to make this a categorical feature

array(['Hyundai Santro Xing XO eRLX Euro III', 'Mahindra Jeep CL550 MDI',
       'Maruti Suzuki Alto 800 Vxi',
       'Hyundai Grand i10 Magna 1.2 Kappa VTVT',
       'Ford EcoSport Titanium 1.5L TDCi', 'Ford Figo', 'Hyundai Eon',
       'Ford EcoSport Ambiente 1.5L TDCi',
       'Maruti Suzuki Alto K10 VXi AMT', 'Skoda Fabia Classic 1.2 MPI',
       'Maruti Suzuki Stingray VXi', 'Hyundai Elite i20 Magna 1.2',
       'Mahindra Scorpio SLE BS IV', 'Audi A8', 'Audi Q7',
       'Mahindra Scorpio S10', 'Maruti Suzuki Alto 800',
       'Hyundai i20 Sportz 1.2', 'Maruti Suzuki Alto 800 Lx',
       'Maruti Suzuki Vitara Brezza ZDi', 'Maruti Suzuki Alto LX',
       'Mahindra Bolero DI', 'Maruti Suzuki Swift Dzire ZDi',
       'Mahindra Scorpio S10 4WD', 'Maruti Suzuki Swift Vdi BSIII',
       'Maruti Suzuki Wagon R VXi BS III',
       'Maruti Suzuki Wagon R VXi Minor',
       'Toyota Innova 2.0 G 8 STR BS IV', 'Renault Lodgy 85 PS RXL',
       'Skoda Yeti Ambition 2.0 TDI CR 4x2',
       'Maru

# CLEANING DATA

In [38]:
backup = car_df.copy()

In [50]:
# FIX FOR YEAR
car_df = car_df[car_df['year'].str.isnumeric()]
car_df['year'] = car_df['year'].astype(int)
car_df['year'].unique()

array([2007, 2006, 2018, 2014, 2015, 2012, 2013, 2016, 2010, 2017, 2008,
       2011, 2019, 2009, 2005, 2000, 2003, 2004, 1995, 2002, 2001])

In [52]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 842 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        842 non-null    object
 1   company     842 non-null    object
 2   year        842 non-null    int64 
 3   Price       842 non-null    object
 4   kms_driven  840 non-null    object
 5   fuel_type   837 non-null    object
dtypes: int64(1), object(5)
memory usage: 46.0+ KB


In [66]:
# FIX FOR PRICE
car_df = car_df[car_df['Price'] != 'Ask For Price']
car_df['Price'] = car_df['Price'].apply(lambda x: x.replace(',', '')).astype(int)
car_df['Price'].unique()

array([  80000,  425000,  325000,  575000,  175000,  190000,  830000,
        250000,  182000,  315000,  415000,  320000, 1000000,  500000,
        350000,  160000,  310000,   75000,  100000,  290000,   95000,
        180000,  385000,  105000,  650000,  689999,  448000,  549000,
        501000,  489999,  280000,  349999,  284999,  345000,  499999,
        235000,  249999, 1475000,  395000,  220000,  170000,   85000,
        200000,  570000,  110000,  448999, 1891111,  159500,  344999,
        449999,  865000,  699000,  375000,  224999, 1200000,  195000,
        351000,  240000,   90000,  155000,  600000,  189500,  210000,
        390000,  135000, 1600000,  701000,  265000,  525000,  372000,
        635000,  550000,  485000,  329500,  251111,  569999,   69999,
        299999,  399999,  450000,  270000,  158400,  179000,  125000,
        299000,  150000,  275000,  285000,  340000,   70000,  289999,
        849999,  749999,  274999,  984999,  599999,  244999,  474999,
        245000,  169

In [64]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 819 entries, 0 to 891
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        819 non-null    object
 1   company     819 non-null    object
 2   year        819 non-null    int64 
 3   Price       819 non-null    int64 
 4   kms_driven  819 non-null    object
 5   fuel_type   816 non-null    object
dtypes: int64(2), object(4)
memory usage: 44.8+ KB


In [ ]:
# FIX KM DRIVEN
car_df = car_df[car_df['kms_driven'] != 'Petrol']

In [87]:
car_df['kms_driven'] = car_df['kms_driven'].str.split(' ').str.get(0).str.replace(',','').astype(int)

In [89]:
car_df['kms_driven'].unique()

array([ 45000,     40,  28000,  36000,  41000,  25000,  24530,  60000,
        30000,  32000,  48660,   4000,  16934,  43000,  35550,  39522,
        39000,  55000,  72000,  15975,  70000,  23452,  35522,  48508,
        15487,  82000,  20000,  68000,  38000,  27000,  33000,  46000,
        16000,  47000,  35000,  30874,  15000,  29685, 130000,  19000,
        54000,  13000,  38200,  22000,  50000,  13500,   3600,  45863,
        60500,  12500,  18000,  13349,  29000,  44000,  42000,  14000,
        49000,  36200,  51000, 104000,  33333,  33600,   5600,   7500,
        26000,  24330,  65480, 200000,  59000,  99000,   2800,  21000,
        11000,  66000,   3000,   7000,  38500,  37200,  43200,  24800,
        45872,  40000,  11400,  97200,  52000,  31000, 175430,  37000,
        65000,   3350,  75000,  62000,  73000,   2200,  54870,  34580,
        97000,     60,  80200,   3200,      0,   5000,    588,  71200,
       175400,   9300,  56758,  10000,  56450,  56000,  32700,   9000,
      

In [100]:
car_df['fuel_type'].dropna(inplace=True)
car_df[car_df['fuel_type'].isna()]

name company  year   Price  kms_driven fuel_type
132  Toyota Corolla  Toyota  2009  275000       26000       NaN

In [106]:
car_df = car_df[~car_df['fuel_type'].isna()]

In [108]:
car_df['fuel_type'].unique()

array(['Petrol', 'Diesel', 'LPG'], dtype=object)

In [113]:
# name fix
car_df['name'] = car_df['name'].str.split(" ").str.slice(0,3).str.join(' ')

In [115]:
car_df.shape

(816, 6)

In [118]:
car_df = car_df.reset_index(drop=True)

In [120]:
car_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 816 entries, 0 to 815
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   name        816 non-null    object
 1   company     816 non-null    object
 2   year        816 non-null    int64 
 3   Price       816 non-null    int64 
 4   kms_driven  816 non-null    int64 
 5   fuel_type   816 non-null    object
dtypes: int64(3), object(3)
memory usage: 38.4+ KB


In [121]:
car_df.describe()

year         Price     kms_driven
count   816.000000  8.160000e+02     816.000000
mean   2012.444853  4.117176e+05   46275.531863
std       4.002992  4.751844e+05   34297.428044
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.912500e+05   56818.500000
max    2019.000000  8.500003e+06  400000.000000

In [126]:
# seems 8.500003e+06	 is outlier
car_df = car_df[car_df['Price'] < 6e6]

In [127]:
car_df.describe()

year         Price     kms_driven
count   815.000000  8.150000e+02     815.000000
mean   2012.442945  4.017933e+05   46277.096933
std       4.005079  3.815888e+05   34318.459638
min    1995.000000  3.000000e+04       0.000000
25%    2010.000000  1.750000e+05   27000.000000
50%    2013.000000  2.999990e+05   41000.000000
75%    2015.000000  4.900000e+05   56879.000000
max    2019.000000  3.100000e+06  400000.000000

In [128]:
# saving clean data
car_df.to_csv('clean_data.csv')

# MODEL BUILDING

In [240]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

In [241]:
ohe = OneHotEncoder()
ohe.fit_transform(car_df[['name', 'company', 'fuel_type']]).toarray()

array([[0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.]])

In [242]:
ohe.get_feature_names_out()

array(['name_Audi A3 Cabriolet', 'name_Audi A4 1.8', 'name_Audi A4 2.0',
       'name_Audi A6 2.0', 'name_Audi A8', 'name_Audi Q3 2.0',
       'name_Audi Q5 2.0', 'name_Audi Q7', 'name_BMW 3 Series',
       'name_BMW 5 Series', 'name_BMW 7 Series', 'name_BMW X1',
       'name_BMW X1 sDrive20d', 'name_BMW X1 xDrive20d',
       'name_Chevrolet Beat', 'name_Chevrolet Beat Diesel',
       'name_Chevrolet Beat LS', 'name_Chevrolet Beat LT',
       'name_Chevrolet Beat PS', 'name_Chevrolet Cruze LTZ',
       'name_Chevrolet Enjoy', 'name_Chevrolet Enjoy 1.4',
       'name_Chevrolet Sail 1.2', 'name_Chevrolet Sail UVA',
       'name_Chevrolet Spark', 'name_Chevrolet Spark 1.0',
       'name_Chevrolet Spark LS', 'name_Chevrolet Spark LT',
       'name_Chevrolet Tavera LS', 'name_Chevrolet Tavera Neo',
       'name_Datsun GO T', 'name_Datsun Go Plus', 'name_Datsun Redi GO',
       'name_Fiat Linea Emotion', 'name_Fiat Petra ELX',
       'name_Fiat Punto Emotion', 'name_Force Motors Force',
    

In [243]:
cat_feature_df = pd.DataFrame(ohe.fit_transform(car_df[['name', 'company', 'fuel_type']]).toarray(),columns=ohe.get_feature_names_out())

In [244]:
final_df = pd.concat([car_df.reset_index(drop=True), cat_feature_df.reset_index(drop=True)], axis=1)
final_df

name   company  year   Price  kms_driven fuel_type  \
0       Hyundai Santro Xing   Hyundai  2007   80000       45000    Petrol   
1       Mahindra Jeep CL550  Mahindra  2006  425000          40    Diesel   
2         Hyundai Grand i10   Hyundai  2014  325000       28000    Petrol   
3    Ford EcoSport Titanium      Ford  2014  575000       36000    Diesel   
4                 Ford Figo      Ford  2012  175000       41000    Diesel   
..                      ...       ...   ...     ...         ...       ...   
810      Maruti Suzuki Ritz    Maruti  2011  270000       50000    Petrol   
811          Tata Indica V2      Tata  2009  110000       30000    Diesel   
812    Toyota Corolla Altis    Toyota  2009  300000      132000    Petrol   
813            Tata Zest XM      Tata  2018  260000       27000    Diesel   
814      Mahindra Quanto C8  Mahindra  2013  390000       40000    Diesel   

     name_Audi A3 Cabriolet  name_Audi A4 1.8  name_Audi A4 2.0  \
0                       0.0               0.0               0.0   
1                       0.0               0.0               0.0   
2                       0.0               0.0               0.0   
3                       0.0               0.0               0.0   
4                       0.0               0.0               0.0   
..                      ...               ...               ...   
810                     0.0               0.0               0.0   
811                     0.0               0.0               0.0   
812                     0.0               0.0               0.0   
813                     0.0               0.0               0.0   
814                     0.0               0.0               0.0   

     name_Audi A6 2.0  ...  company_Nissan  company_Renault  company_Skoda  \
0                 0.0  ...             0.0              0.0            0.0   
1                 0.0  ...             0.0              0.0            0.0   
2                 0.0  ...             0.0              0.0            0.0   
3                 0.0  ...             0.0              0.0            0.0   
4                 0.0  ...             0.0              0.0            0.0   
..                ...  ...             ...              ...            ...   
810               0.0  ...             0.0              0.0            0.0   
811               0.0  ...             0.0              0.0            0.0   
812               0.0  ...             0.0              0.0            0.0   
813               0.0  ...             0.0              0.0            0.0   
814               0.0  ...             0.0              0.0            0.0   

     company_Tata  company_Toyota  company_Volkswagen  company_Volvo  \
0             0.0             0.0                 0.0            0.0   
1             0.0             0.0                 0.0            0.0   
2             0.0             0.0                 0.0            0.0   
3             0.0             0.0                 0.0            0.0   
4             0.0             0.0                 0.0            0.0   
..            ...             ...                 ...            ...   
810           0.0             0.0                 0.0            0.0   
811           1.0             0.0                 0.0            0.0   
812           0.0             1.0                 0.0            0.0   
813           1.0             0.0                 0.0            0.0   
814           0.0             0.0                 0.0            0.0   

     fuel_type_Diesel  fuel_type_LPG  fuel_type_Petrol  
0                 0.0            0.0               1.0  
1                 1.0            0.0               0.0  
2                 0.0            0.0               1.0  
3                 1.0            0.0               0.0  
4                 1.0            0.0               0.0  
..                ...            ...               ...  
810               0.0            0.0               1.0  
811               1.0            0.

In [245]:
x = final_df.drop(columns=['Price','name', 'company', 'fuel_type'])
y = final_df['Price']
print(x)
print(y)

     year  kms_driven  name_Audi A3 Cabriolet  name_Audi A4 1.8  \
0    2007       45000                     0.0               0.0   
1    2006          40                     0.0               0.0   
2    2014       28000                     0.0               0.0   
3    2014       36000                     0.0               0.0   
4    2012       41000                     0.0               0.0   
..    ...         ...                     ...               ...   
810  2011       50000                     0.0               0.0   
811  2009       30000                     0.0               0.0   
812  2009      132000                     0.0               0.0   
813  2018       27000                     0.0               0.0   
814  2013       40000                     0.0               0.0   

     name_Audi A4 2.0  name_Audi A6 2.0  name_Audi A8  name_Audi Q3 2.0  \
0                 0.0               0.0           0.0               0.0   
1                 0.0               0.0      

In [250]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [247]:
lr = LinearRegression()
lr.fit(x_train, y_train)

LinearRegression()

In [251]:
y_pred = lr.predict(x_test)
r2_score(y_test, y_pred)

0.8984327057398095

In [252]:
import pickle
pickle.dump(lr, open('model_l.pkl', 'wb'))

# USING PIPELINE

In [253]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split


from sklearn.compose import make_column_transformer
from sklearn.pipeline import make_pipeline

In [254]:
x = car_df.drop(columns=['Price'])
y = car_df['Price']
print(x)
print(y)

                       name   company  year  kms_driven fuel_type
0       Hyundai Santro Xing   Hyundai  2007       45000    Petrol
1       Mahindra Jeep CL550  Mahindra  2006          40    Diesel
2         Hyundai Grand i10   Hyundai  2014       28000    Petrol
3    Ford EcoSport Titanium      Ford  2014       36000    Diesel
4                 Ford Figo      Ford  2012       41000    Diesel
..                      ...       ...   ...         ...       ...
811      Maruti Suzuki Ritz    Maruti  2011       50000    Petrol
812          Tata Indica V2      Tata  2009       30000    Diesel
813    Toyota Corolla Altis    Toyota  2009      132000    Petrol
814            Tata Zest XM      Tata  2018       27000    Diesel
815      Mahindra Quanto C8  Mahindra  2013       40000    Diesel

[815 rows x 5 columns]
0       80000
1      425000
2      325000
3      575000
4      175000
        ...  
811    270000
812    110000
813    300000
814    260000
815    390000
Name: Price, Length: 815, dtyp

In [255]:
ohe = OneHotEncoder()
ohe.fit(x[['name', 'company', 'fuel_type']])

OneHotEncoder()

In [270]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [257]:
transformer = make_column_transformer((OneHotEncoder(categories=ohe.categories_), 
                                      ['name', 'company', 'fuel_type']),
                                      remainder='passthrough')

linear_regression = LinearRegression()
pipeline = make_pipeline(transformer, linear_regression)

In [271]:
pipeline.fit(x_train, y_train)

/Users/r0c0hjm/DATA_ML_TEAM/machine_learning/CAR_PRICE_PREDICTOR/car_price/lib/python3.9/site-packages/sklearn/compose/_column_transformer.py:1651: FutureWarning: 
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(categories=[array(['Audi A3 Cabriolet', 'Audi A4 1.8', 'Audi A4 2.0', 'Audi A6 2.0',
       'Audi A8', 'Audi Q3 2.0', 'Audi Q5 2.0', 'Audi Q7', 'BMW 3 Series',
       'BMW 5 Series', 'BMW 7 Series', 'BMW X1', 'BMW X1 sDrive20d',
       'BMW X1 xDrive20d', 'Chevrolet Beat', 'Chevrolet Beat...
                                                                            array(['Audi', 'BMW', 'Chevrolet', 'Datsun', 'Fiat', 'Force', 'Ford',
       'Hindustan', 'Honda', 'Hyundai', 'Jaguar', 'Jeep', 'Land',
       'Mahindra', 'Maruti', 'Mercedes', 'Mini', 'Mitsubishi', 'Nissan',
       'Renault', 'Skoda', 'Tata', 'Toyota', 'Volkswagen', 'Volvo'],
      dtype=object),
                                                                            array(['Diesel', 'LPG', 'Petrol'], dtype=object)]),
                                                  ['name', 'company',
                                                   'fuel_type'])])),
                ('linearregression', LinearRegression())])

In [272]:
y_pred = pipeline.predict(x_test)
r2_score(y_test, y_pred)

0.5469247720429827

In [260]:
import pickle
pickle.dump(pipeline, open('model.pkl', 'wb'))

In [274]:
pipeline.predict(pd.DataFrame([['Hyundai Santro Xing', 'Hyundai', 2006, 100, 'Petrol']], 
                              columns=['name', 'company', 'year',  'kms_driven', 'fuel_type']))

array([164425.06879654])